MGNREGACON/Controllers/ConvergenceController.cs
using MLAFund.Models;
using MLAFund.Models.Data;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.UI;
using System.Runtime.Remoting.Contexts;
using System.Web.Routing;

namespace Grievance.Controllers
{
    public class ConvergenceController : Controller
    {

        public RuralWorksData data = new RuralWorksData();
        // GET: CompletedScheme

        public string result;

        public ActionResult Create()
        {
            var user = User.Identity.Name;
            var user_data = User.UserData();
            //ViewData["userid"] = user;
            return View();
        }

        public ActionResult UploadFiles()
        {
            string fname = "";

            if (Request.Files.Count > 0)
            {
                try
                {
                    string txtname = Request.Files["txtname"].ToString();

                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];

                        string extension = Path.GetExtension(file.FileName);

                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {

                            fname = txtname.Trim() + file.FileName;
                        }
                        else
                        {
                            fname = txtname.Trim() + file.FileName;
                        }
                        var dir = Server.MapPath("~/Content/convergence/");
                        DirectoryInfo info = new DirectoryInfo(dir);
                        if (!info.Exists) info.Create();
                        var fpathAndfile = Path.Combine(dir, fname);
                        file.SaveAs(fpathAndfile);

                    }

                    return Json(new { status = "OK", Message = "File Uploaded Successfully!", file = "~/Content/convergence/" + fname });
                }
                catch (Exception ex)
                {
                    return Json(new { status = "failed", Message = "Error occurred. Error details: " + ex.Message });
                }
            }
            else
            {
                return Json(new { status = "Failed", Message = "No files selected." });
            }
        }

       
        public ActionResult Index()
        {
            var result = data.convergence.ToList();
            return View(result);
        }

        public ActionResult WorkProgress()
        {
            //Nishant - Work Progress Entry - Start
            //Comments : This would fetch the record from the workprogress table where
            //           for the user which is logged in.
            var userLoggedIn = User.Identity.Name;
            var result = data.workprogress
                .OrderByDescending(y => y.date)
                .Where(i => i.submittedby == userLoggedIn)
                .ToList()
                .FirstOrDefault();
            return View(result);

            //Nishant - Work Progress Entry - End
        }

        
     
        public ActionResult MLAFund_Utilization_Report()
        {
            var dis = User.GetUserDistrict();
            var userLoggedIn = User.Identity.Name;

            //var selected_district = sno;

            
            var assembly_name = data.tbl_Users
                .Where(x => x.username == userLoggedIn)
                .Select(o => o.assembly_name).SingleOrDefault();


            if (dis == "State")
            {

                var result = data.mla_expenses
                    .ToList()
                    .AsQueryable();

                result = result.OrderBy(k => k.assembly_name);
                return View(result);


            }

            else
            {
                var result = data.mla_expenses
                .Where(i => i.assembly_name == assembly_name)
                .ToList()
                .AsQueryable();
                result = result.OrderBy(k => k.financial_year);
                return View(result);

            }

        }

        //Nishant - Added Report for Selecting Completed Convergence Records
        public ActionResult CompleteConvergenceReport()
        {

            var dis = User.GetUserDistrict();
            var userLoggedIn = User.Identity.Name;
            var user_dpt_name = data.tbl_Users
                .Where(x => x.username == userLoggedIn);
               // .Select(o => o.dpt_name).SingleOrDefault();

            if (dis == "State")
            {
                var result = data.convergence.Include(o => o.convergencedpt)
               .Where(i => i.status == "complete")
               .ToList()
               .AsQueryable();

                result = result.OrderBy(k => k.cid);

                return View(result);

            }
            else
            {
                var result = data.convergence.Include(o => o.convergencedpt)
                .Where(i => i.district == dis && i.status == "complete")
                .ToList()
                .AsQueryable();

                result = result.OrderBy(k => k.cid);
                return View(result);
            }


        }

        //Nishant - Added code for saving Convergence Fund details from Add Convergence Fund PopUp - Start
        [HttpPost]
        public ActionResult AddConvergenceFund(int popup_cid, int popup_convergenceFund, string popup_convergenceDeptName, string popup_convergenceDeptScheme)
        {
            //Selecting the record from the ConvergenceDpt table
            var updateConvergenceDpt = data.convergencedpt.Where(x => x.cid == popup_cid && x.convergencedptname == popup_convergenceDeptName
            && x.convergencedptscheme == popup_convergenceDeptScheme).FirstOrDefault();
            updateConvergenceDpt.convergencefund = popup_convergenceFund;
            data.Entry(updateConvergenceDpt).State = System.Data.Entity.EntityState.Modified;
            data.SaveChanges();

            //Selecting the record from Convergence table to update the status to complete
            var updateConvergence = data.convergence.Where(x => x.cid == popup_cid).FirstOrDefault();
            updateConvergence.status = "Complete";
            data.Entry(updateConvergence).State = System.Data.Entity.EntityState.Modified;
            data.SaveChanges();


            return Json(new { success = true, responseText = "Saved successfuly ", responseid = 1 }, JsonRequestBehavior.AllowGet);

        }
        //Nishant - Added code for saving Convergence Fund details from Add Convergence Fund PopUp - End

        public ActionResult dptReport()
        {
            var userLoggedIn = User.Identity.Name;
            var result = data.workprogress
                .Where(i => i.submittedby == userLoggedIn)
                .ToList();
            return View(result);
        }

        //Nishant - State Department Report
        //Comments: This would genereate a report for the Departments and the number of Pending Convergence Cases.
        
        public ActionResult stateDptReport()
        {

            var result = data.convergence
                        .Join(data.convergencedpt, converge => converge.cid, convergedpt => convergedpt.cid, (converge, convergedpt) => new { converge, convergedpt })
                        //.Where(o =>  o.converge.status == "pending")
                        .GroupBy(x => new { x.convergedpt.convergencedptname })
                        .Select(g => new stateDeptReport()
                        {
                            convergenceDptName = g.Key.convergencedptname,
                            pending = g.Sum(t=>t.converge.status == "Pending" ?1:0  ),
                            completed = g.Sum(t => t.converge.status == "Complete" ? 1 : 0),
                        }).ToList();

            return View(result);
        }

        public ActionResult WorkProgressReport()
        {
            var dis = User.GetUserDistrict();
            var userLoggedIn = User.Identity.Name;
            var user_dpt_name = data.tbl_Users
                .Where(x => x.username == userLoggedIn);
                //.Select(o => o.dpt_name).SingleOrDefault();

            if (dis == "State")
            {
                var result = data.convergence
                    .Join(data.workprogress_app, converge => converge.cid, wrkprg => wrkprg.cid, (converge, wrkprg) => new { converge, wrkprg })
                    .Select(g => new wrkPrgReport()
                    {
                        district = g.converge.district,
                        block= g.converge.block,
                        panchayat=g.converge.panchayat,
                        village=g.converge.village,
                        nameofscheme=g.converge.nameofscheme,
                        fundofdpt=g.converge.fundofdpt,
                        fundofmgnrega=g.converge.fundofmgnrega,
                        latitude=g.wrkprg.latitude,
                        longitude=g.wrkprg.longitude,
                        photo1 = g.wrkprg.photo1,
                        photo2 = g.wrkprg.photo2,
                        photo3 = g.wrkprg.photo3,
                        address =g.wrkprg.address,
                    }).ToList();
                return View(result);

            }
            else
            {
               return RedirectToAction("Index","Home");
            }

        }

    }
}

MGNREGACON/Controllers/FundAllotmentController.cs
using MLAFund.Models;
using MLAFund.Models.Data;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.UI;
using System.Runtime.Remoting.Contexts;
using System.Web.Routing;

namespace Grievance.Controllers
{
    public class FundAllotmentController : Controller
    {

        public RuralWorksData data = new RuralWorksData();
        // GET: CompletedScheme

        public string result;

        public ActionResult Create()
        {
            var user = User.Identity.Name;
            var user_data = User.UserData();
            //ViewData["userid"] = user;
            return View();
        }

        public ActionResult CreateExpense(string financial_year)
        {
            ViewBag.financial_year = financial_year;
            return View();
        }

        public ActionResult MLAFundAllotmentReport()
        {
            //Nishant - Fund Allotment Report - Start
            //Comments : This would fetch the record from the fund Allotment table where
            //           for the user which is logged in.
            //          This would only work for State login.

            var dis = User.GetUserDistrict();
            if(dis == "State") {
                var result = data.fund_allotment
                    .OrderByDescending(y => y.fundallotmentid)
                    .ToList()
                    .AsQueryable();
                return View(result);
            }
            return View();

            //Nishant - Fund Allotment Report - End
        }


        public ActionResult MLAFAssemblyExpenseReport()
        {
            var dis = User.GetUserDistrict();
            if (dis == "State")
            {
                var result = data.mla_expenses
                      .GroupBy(x => new { x.assembly_name, x.financial_year })
                      .Select(g => new mla_expenses_temp()
                      {
                          assembly_name = g.Key.assembly_name,
                          financial_year = g.Key.financial_year,
                          total_expense_amount = g.Sum(t => t.expense_amount),
                      }).ToList();
                return View(result);
            }
           
                return View(result);

        }

        public ActionResult MLAFund_Utilization_Report(string financial_year)
        {
            var dis = User.GetUserDistrict();
            var userLoggedIn = User.Identity.Name;

            //var selected_district = sno;


            var assembly_name = data.tbl_Users
                .Where(x => x.username == userLoggedIn)
                .Select(o => o.assembly_name).SingleOrDefault();

            var mla_name = data.tbl_Users
                            .Where(x => x.assembly_name == assembly_name)
                             .Select(o => o.mla_name).SingleOrDefault();

            ViewBag.AssemblyName = assembly_name;
            ViewBag.MLAName = mla_name;

            if (dis == "State")
            {

                var result = data.mla_expenses
                    .ToList()
                    .AsQueryable();

                result = result.OrderBy(k => k.assembly_name);
                return View(result);
            }

            else
            {
                var result = data.mla_expenses
                .Where(i => i.assembly_name == assembly_name && i.financial_year == financial_year)
                .ToList()
                .AsQueryable();
                result = result.OrderBy(k => k.financial_year);
                return View(result);
            }

        }

        //Nishant - Added code for Expense details report for State - Code Start
        public ActionResult DetailedExpenseReport(string assembly_name, string financial_year)
        {
            var dis = User.GetUserDistrict();
            if(dis == "State")
            {
                var result = data.mla_expenses
                    .Where(x =>x.assembly_name == assembly_name && x.financial_year == financial_year)
                    .OrderBy(y =>y.expensesid)
                    .ToList()
                    .AsQueryable();

                return View(result);
            }

            return View();  

        }
        //Nishant - Added code for Expense details report for State - Code End


        public ActionResult Assembly_FundAllotment()
        {
            var userLoggedIn = User.Identity.Name;

            var assembly_name = data.tbl_Users
                .Where(x => x.username == userLoggedIn)
                .Select(o => o.assembly_name).SingleOrDefault();

            IQueryable<fund_allotment> result = data.fund_allotment
                .Where(x => x.assembly_name == assembly_name)
                .OrderBy(y => y.financial_year)
                .ToList()
                .AsQueryable();

            return View(result);
        }

        public void updateTotalExpenditure(string financial_year, string assembly_name)
        {
            var temp_data = false;
            if (!temp_data)
            {
                var total_expense = data.mla_expenses
                    .Where(x => x.assembly_name == assembly_name && x.financial_year == financial_year)
                    .Sum(x => x.expense_amount).ToString();
                //select the record from Fund Allocated table
                var record = data.fund_allotment.Where(x => x.assembly_name == assembly_name && x.financial_year == financial_year).FirstOrDefault();
                record.total_expenditure = int.Parse(total_expense);
                data.Entry(record).State = EntityState.Modified;
                data.SaveChanges();
            }
        }


        //Nishant - Added code for Uploading Expenses doc  : Code Start
        public ActionResult UploadFiles()
        {
            string fname = "";

            if (Request.Files.Count > 0)
            {
                try
                {
                    string txtname = Request.Files["txtname"].ToString();

                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];

                        string extension = Path.GetExtension(file.FileName);

                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {

                            fname = txtname.Trim() + file.FileName;
                        }
                        else
                        {
                            fname = txtname.Trim() + file.FileName;
                        }
                        var dir = Server.MapPath("~/Content/FundAllotedDocs/");
                        DirectoryInfo info = new DirectoryInfo(dir);
                        if (!info.Exists) info.Create();
                        var fpathAndfile = Path.Combine(dir, fname);
                        file.SaveAs(fpathAndfile);

                    }

                    return Json(new { status = "OK", Message = "File Uploaded Successfully!", file = "~/Content/FundAllotedDocs/" + fname });
                }
                catch (Exception ex)
                {
                    return Json(new { status = "failed", Message = "Error occurred. Error details: " + ex.Message });
                }
            }
            else
            {
                return Json(new { status = "Failed", Message = "No files selected." });
            }
        }
        //Nishant - Added code for Uploading Expenses doc  : Code End


    }
}

MGNREGACON/Views/FundAllotment/Assembly_FundAllotment.cshtml
@model IEnumerable<MLAFund.Models.Data.fund_allotment>

@{
    ViewBag.Title = "Fund Allotment - Year Wise";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section bc{

    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="Home/Index">Home</a></li>
        <li class="breadcrumb-item active">Index</li>
    </ol>


}

<div class="col-md-12 col-lg-12">
    <div class="card card-dark">
        <div class="card-header">
            <h3 class="card-title"> Allotment Summary </h3>
        </div>

        <table id="mlafund_allotment" class="table Items table-bordered table-responsive container--fluid" style="width:" 100px">
            <thead>
                <tr class="bg-secondary">
                    <th style="width: 1%">Sr.No</th>
                    <th>Financial Year</th>
                    <th>Allotment Amount</th>
                    <th>Expenditure Amount</th>
                    <th>Actions</th>

                </tr>
            </thead>

            @if (Model != null)
            {

                <tbody>

                    @foreach (var item in Model.Select((i, it) => new { i, it = it + 1 }))
                    {

                        <tr>
                            <td>@item.it</td>
                            <td>@item.i.financial_year</td>
                            <td>@item.i.allotted_fund</td>
                            <td>@item.i.total_expenditure</td>
                            <td class="btn">
                                @Html.ActionLink("Add Expense", "CreateExpense", new {financial_year = @item.i.financial_year })
                            </td>
                            <td class="btn">
                                @Html.ActionLink("View Expense", "MLAFund_Utilization_Report", new {financial_year = @item.i.financial_year })
                            </td>
                        </tr>
                    }
                </tbody>
            }


        </table>
    </div>
</div>

@section scripts{
    <style>
        [v-cloak] {
            display: none;
        }
    </style>

    <!--Nishant : Code Start: Added Code for Datatables-->
    <script>
        /* The below code was for exporting table data to an excel */
        /*
       function ExportToExcel(type, fn, dl) {
            var elt = document.getElementById('mlafund_utilization_report');
            var wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });
            return dl ?
                XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }) :
                XLSX.writeFile(wb, fn || ('MLAFund Utilization Report.' + (type || 'xlsx')));
        }
        */
        $(document).ready(function () {
            var table = $('#mlafund_allotment',).DataTable({
                //Toggle the below paging to false - to remove pagination
                pageLength: 5,
                paging: true,

                //Nishant Code Start - Code Add for Exporting to PDF
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'pdfHtml5',
                        orientation: 'portrait',
                        title: 'MLA Fund Allotment Report',
                        pageSize: 'A4',
                        text: 'Export to PDF'
                    }
                ]
                //Code End - Code Added for File Export to PDF

            });

            $('a.toggle-vis').on('click', function (e) {
                e.preventDefault();

                // Get the column API object
                var column = table.column($(this).attr('data-column'));

                // Toggle the visibility
                column.visible(!column.visible());
            });
        });
    </script>
    <!--Nishant : Code Start: Added Code for Datatables-->

    <script src="~/Scripts/axios/axios.min.js"></script>
    <script src="~/Scripts/vue/vue.min.js"></script>
    <script src="~/Scripts/vee-validate/vee-validate.min.js"></script>
    <script>Vue.use(VeeValidate);</script>
    <script src="~/Scripts/apps/convergence.js"></script>



}

MGNREGACON/Views/FundAllotment/WorkProgress.cshtml
@using MLAFund.Models.Data
@model workprogress

@{
    ViewBag.Title = "Convergence - Work Progress";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*@section bc{

        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/convergence">convergence</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>


    }*@
<div class="col-md-12 col-lg-12" id="app" v-cloak>
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">
                Add New WorkProgress Entry
            </h3>
        </div>
        <div class="card-body">
            <div class="row ">

                @* Table - Start *@
                <table id="workprogress_entry" class="table table-bordered table-striped Items table-responsive" style="width:100%">
                    <thead>
                        <tr class="bg-secondary">
                            <th colspan="3">
                                <h4>Fund Utilization Details</h4>
                            </th>
                        </tr>
                        <tr>
                            <th style="width: 15%">#</th>
                            <th>Previous Entry Data</th>
                            <th>Current Entry Data</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <label for="fundUtilizedDept">Department Fund Utilized</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.fundutilizeddept, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="text" required class="form-control" v-model="workprogress.fundutilizeddept" />
                            </td>

                        </tr>
                        <tr>
                            <td>
                                <label for="fundutilizedMgnrega">MGNREGA Fund Utilized</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.fundutilizedmgnrega, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="text" required class="form-control" v-model="workprogress.fundutilizedmgnrega" />
                            </td>

                        </tr>
                        <tr>
                            <td>
                                <label for="fundUtilized">Total Fund Utilized</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.fundutilized, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="text" required class="form-control" v-model="workprogress.fundutilized" />
                            </td>

                        </tr>
                        <tr>
                            <td>
                                <label for="dateOfUtilization">Date of Utilization</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.dateofutilization, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="date" required class="form-control" v-model="workprogress.dateofutilization" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="workStatus">Status of Work</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.workstatus, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <select class="form-control select2" v-model="workprogress.workstatus">
                                    <option value="Not Started">Not Started</option>
                                    <option value="Ongoing">Ongoing</option>
                                    <option value="Completed">Completed</option>
                                    <option value="Not Completed">Not Completed</option>
                                    <option value="Others">Others</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="mandaysGenerated">No. of Mandays Generated</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.mandaysgenerated, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="text" required class="form-control" v-model="workprogress.mandaysgenerated" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="remarks">Remarks</label>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => model.remarks, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            </td>
                            <td>
                                <input type="text" required class="form-control" v-model="workprogress.remarks" />
                            </td>
                        </tr>
                    </tbody>
                </table>
                @* Table - End *@

               
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="geotagPhotoUpload">Upload Photo</label>
                            <input type="file" id="filename_c" value="No Files Chosen" ref="gg" />
                            @*<input type="button" id="btnUpload" value="Upload PDF" class="btn btn-info" />*@
                        </div>

                    </div>
                </div>



                @* Form End here *@

                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">@Session["district"]</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <div class="box-body">

                            <!---wizard-->
                            <!---end wizard-->



                        </div>
                        <!-----boxend-->
                        <!--<div class="box-body">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="exampleInputPassword1">PDF Upload</label>
                    <input type="file" id="filename_c" value="No Files Chosen" ref="gg" />-->
                        @*<input type="button" id="btnUpload" value="Upload PDF" class="btn btn-info" />*@
                        <!--</div>

                </div>
            </div>-->
                        <!-- /.box-body -->
                        <div class="box-footer">
                            @*<input type="button" value="Submit" class="btn btn-primary" @@click="saveData()" />*@

                            <button type="button" class="btn btn-primary" @@click="saveData()" v-bind:disabled="busy">
                                <i class="fas fa-spinner fa-spin" v-if="busy"></i>
                                Submit
                            </button>
                            <a href="@Url.Action("WorkProgressReport","Convergence")" class="btn btn-success">View</a>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger", @required = "true" })
                            <div class="pad margin no-print">

                                @ViewBag.Msg
                            </div>
                        </div>

                    </div>

                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
        </div>

        <!-- /.card-header -->
        <!-- form start -->

    </div>
</div>





@section scripts{
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    <script src="~/Scripts/axios/axios.min.js"></script>
    <script src="~/Scripts/vue/vue.min.js"></script>
    <script src="~/Scripts/vee-validate/vee-validate.min.js"></script>
    <script>Vue.use(VeeValidate);</script>
    <script src="~/Scripts/apps/WorkProgress.js"></script>
}